---
# asdf shell tasks
- name: Check whether fish config dir exists
  stat:
    path: "{{ asdf_fish_config_dir }}"
  register: asdf_fish_config_dir_st

- name: Copy fish completions
  copy:
    src: "{{ asdf_dir }}/internal/completions/asdf.fish"
    dest: "{{ asdf_home }}/.config/fish/completions/asdf.fish"
    remote_src: true
  when:
    - asdf_fish_config_dir_st.stat.exists
