complete -c himalaya -n "__fish_use_subcommand" -s c -l config -d 'Forces a specific config path'
complete -c himalaya -n "__fish_use_subcommand" -s a -l account -d 'Selects a specific account'
complete -c himalaya -n "__fish_use_subcommand" -s o -l output -d 'Defines the output format' -r -f -a "plain json"
complete -c himalaya -n "__fish_use_subcommand" -s l -l log-level -d 'Defines the logs level' -r -f -a "error warn info debug trace"
complete -c himalaya -n "__fish_use_subcommand" -s m -l mailbox -d 'Selects a specific mailbox'
complete -c himalaya -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_use_subcommand" -f -a "completion" -d 'Generates the completion script for the given shell'
complete -c himalaya -n "__fish_use_subcommand" -f -a "notify" -d 'Notifies when new messages arrive in the given mailbox'
complete -c himalaya -n "__fish_use_subcommand" -f -a "watch" -d 'Watches IMAP server changes'
complete -c himalaya -n "__fish_use_subcommand" -f -a "mailboxes" -d 'Lists all mailboxes'
complete -c himalaya -n "__fish_use_subcommand" -f -a "flag" -d 'Handles flags'
complete -c himalaya -n "__fish_use_subcommand" -f -a "template" -d 'Generates a message template'
complete -c himalaya -n "__fish_use_subcommand" -f -a "attachments" -d 'Downloads all message attachments'
complete -c himalaya -n "__fish_use_subcommand" -f -a "list" -d 'Lists all messages'
complete -c himalaya -n "__fish_use_subcommand" -f -a "search" -d 'Lists messages matching the given IMAP query'
complete -c himalaya -n "__fish_use_subcommand" -f -a "write" -d 'Writes a new message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "send" -d 'Sends a raw message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "save" -d 'Saves a raw message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "read" -d 'Reads text bodies of a message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "reply" -d 'Answers to a message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "forward" -d 'Forwards a message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "copy" -d 'Copies a message to the targetted mailbox'
complete -c himalaya -n "__fish_use_subcommand" -f -a "move" -d 'Moves a message to the targetted mailbox'
complete -c himalaya -n "__fish_use_subcommand" -f -a "delete" -d 'Deletes a message'
complete -c himalaya -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c himalaya -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from completion" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from notify" -s k -l keepalive -d 'Specifies the keepalive duration'
complete -c himalaya -n "__fish_seen_subcommand_from notify" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from notify" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from watch" -s k -l keepalive -d 'Specifies the keepalive duration'
complete -c himalaya -n "__fish_seen_subcommand_from watch" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from watch" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from mailboxes" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from mailboxes" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from flag" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from flag" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from flag" -f -a "add" -d 'Adds flags to a message'
complete -c himalaya -n "__fish_seen_subcommand_from flag" -f -a "set" -d 'Replaces all message flags'
complete -c himalaya -n "__fish_seen_subcommand_from flag" -f -a "remove" -d 'Removes flags from a message'
complete -c himalaya -n "__fish_seen_subcommand_from flag" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c himalaya -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from template" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from template" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from template" -f -a "new" -d 'Generates a new message template'
complete -c himalaya -n "__fish_seen_subcommand_from template" -f -a "reply" -d 'Generates a reply message template'
complete -c himalaya -n "__fish_seen_subcommand_from template" -f -a "forward" -d 'Generates a forward message template'
complete -c himalaya -n "__fish_seen_subcommand_from template" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s s -l subject -d 'Overrides the Subject header'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s f -l from -d 'Overrides the From header'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s t -l to -d 'Overrides the To header'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s c -l cc -d 'Overrides the Cc header'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s b -l bcc -d 'Overrides the Bcc header'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s h -l header -d 'Overrides a specific header'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s B -l body -d 'Overrides the body'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s S -l signature -d 'Overrides the signature'
complete -c himalaya -n "__fish_seen_subcommand_from new" -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from new" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s s -l subject -d 'Overrides the Subject header'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s f -l from -d 'Overrides the From header'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s t -l to -d 'Overrides the To header'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s c -l cc -d 'Overrides the Cc header'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s b -l bcc -d 'Overrides the Bcc header'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s h -l header -d 'Overrides a specific header'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s B -l body -d 'Overrides the body'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s S -l signature -d 'Overrides the signature'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s A -l all -d 'Includes all recipients'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s s -l subject -d 'Overrides the Subject header'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s f -l from -d 'Overrides the From header'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s t -l to -d 'Overrides the To header'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s c -l cc -d 'Overrides the Cc header'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s b -l bcc -d 'Overrides the Bcc header'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s h -l header -d 'Overrides a specific header'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s B -l body -d 'Overrides the body'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s S -l signature -d 'Overrides the signature'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from attachments" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from attachments" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from list" -s s -l size -d 'Page size'
complete -c himalaya -n "__fish_seen_subcommand_from list" -s p -l page -d 'Page number'
complete -c himalaya -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from search" -s s -l size -d 'Page size'
complete -c himalaya -n "__fish_seen_subcommand_from search" -s p -l page -d 'Page number'
complete -c himalaya -n "__fish_seen_subcommand_from search" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from search" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from write" -s a -l attachment -d 'Adds attachment to the message'
complete -c himalaya -n "__fish_seen_subcommand_from write" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from write" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from send" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from send" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from save" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from save" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from read" -s t -l mime-type -d 'MIME type to use' -r -f -a "plain html"
complete -c himalaya -n "__fish_seen_subcommand_from read" -s r -l raw -d 'Reads raw message'
complete -c himalaya -n "__fish_seen_subcommand_from read" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from read" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s a -l attachment -d 'Adds attachment to the message'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s A -l all -d 'Includes all recipients'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from reply" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s a -l attachment -d 'Adds attachment to the message'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from forward" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from copy" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from copy" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from move" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from move" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from delete" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from delete" -s V -l version -d 'Prints version information'
complete -c himalaya -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c himalaya -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
