complete -c todors -n "__fish_use_subcommand" -s d -d 'Location of toml config file' -r
complete -c todors -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_use_subcommand" -s @ -d 'Hide task contexts from output'
complete -c todors -n "__fish_use_subcommand" -s + -d 'Hide task projects from output'
complete -c todors -n "__fish_use_subcommand" -s c -d 'Color mode'
complete -c todors -n "__fish_use_subcommand" -s f -d 'Force actions without confirmation or input'
complete -c todors -n "__fish_use_subcommand" -s P -d 'Hide task priorities from output'
complete -c todors -n "__fish_use_subcommand" -s n -d 'Don\'t preserve line (task) numbers'
complete -c todors -n "__fish_use_subcommand" -s N -d 'Preserve line (task) numbers'
complete -c todors -n "__fish_use_subcommand" -s p -d 'Plain mode turns off colors'
complete -c todors -n "__fish_use_subcommand" -s v -d 'Increase log verbosity printed to console'
complete -c todors -n "__fish_use_subcommand" -s q -d 'Quiet debug messages on console'
complete -c todors -n "__fish_use_subcommand" -s t -d 'Prepend current date to new task'
complete -c todors -n "__fish_use_subcommand" -s T -d 'Don\'t prepend current date to new task'
complete -c todors -n "__fish_use_subcommand" -f -a "add" -d 'Adds a line of text to todo.txt'
complete -c todors -n "__fish_use_subcommand" -f -a "addm" -d 'Adds multiple lines of text to todo.txt'
complete -c todors -n "__fish_use_subcommand" -f -a "addto" -d 'Adds a line of text to any file located in the todo.txt directory'
complete -c todors -n "__fish_use_subcommand" -f -a "append" -d 'Adds text to end of task'
complete -c todors -n "__fish_use_subcommand" -f -a "archive" -d 'Moves all done tasks from todo.txt to done.txt and removes blank lines'
complete -c todors -n "__fish_use_subcommand" -f -a "complete" -d 'Generates shell completions to stdout'
complete -c todors -n "__fish_use_subcommand" -f -a "deduplicate" -d 'Removes duplicate lines from todo.txt'
complete -c todors -n "__fish_use_subcommand" -f -a "del" -d 'Deletes a task or part of a task from todo.txt'
complete -c todors -n "__fish_use_subcommand" -f -a "depri" -d 'Deprioritizes (removes the priority) from the task(s) on line ITEM in todo.txt'
complete -c todors -n "__fish_use_subcommand" -f -a "list" -d 'Displays all the lines in todo.txt with optional filtering'
complete -c todors -n "__fish_use_subcommand" -f -a "listall" -d 'Displays all lines in todo.txt AND done.txt with optional filtering'
complete -c todors -n "__fish_use_subcommand" -f -a "listpri"
complete -c todors -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c todors -n "__fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from add" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from addm" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from addm" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from addto" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from addto" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from append" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from append" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from archive" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from archive" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from complete" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from complete" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from deduplicate" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from deduplicate" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from del" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from del" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from depri" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from depri" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from list" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from listall" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from listall" -s V -l version -d 'Print version information'
complete -c todors -n "__fish_seen_subcommand_from listpri" -s h -l help -d 'Print help information'
complete -c todors -n "__fish_seen_subcommand_from listpri" -s V -l version -d 'Print version information'
