---
# defaults file for env
# vim:ft=yaml.ansible:
env_fish_env_file: $XDG_CONFIG_HOME/fish/conf.d/01_env.fish
env_bash_env_file: $XDG_CONFIG_HOME/bash/conf.d/01_env.bash
env_zsh_env_file: $XDG_CONFIG_HOME/zsh/conf.d/01_env.zsh

env_paths:
  - /opt/homebrew/bin
  - /usr/local/go/bin
  - $HOME/go/bin
  - $HOME/.cargo/bin
  - $HOME/.fzf/bin
  - $HOME/.asdf/bin
  - $HOME/.luarocks/bin
  - $HOME/.gem/ruby/2.7.0/bin
  - $HOME/.local/bin
  - $HOME/bin

env_vars:
  - {key: LD_LIBRARY_PATH, val: $HOME/.local/lib}
  - {key: MANPATH, val: '$HOME/.local/share/man:'}
  - {key: PKG_CONFIG_PATH, val: $HOME/.local/lib/pkgconfig}
  - {key: LANG, val: en_US.utf8}
  - {key: XDG_CONFIG_HOME, val: $HOME/.config}
  - {key: XDG_CACHE_HOME, val: $HOME/.cache}
  - {key: XDG_DATA_HOME, val: $HOME/.local/share}
  - {key: LC_ALL, val: en_US.utf-8}
  - {key: BROWSER, val: w3m, if: which w3m}
  - {key: ARCH, val: uname -m, eval: true}
  - {key: CLICOLOR, val: 1}
  - {key: LS_AFTER_CD, val: 0}
  - {key: LS_AFTER_CD_COMMAND, val: eza -a --group-directories-first}
  - {key: TODOTXT_CFG_FILE, val: $HOME/Dropbox/todo/todo.cfg}
  - {key: TODORS_CFG_FILE, val: $HOME/Dropbox/todo/todo.toml}
  - {key: NVIM_PY3_DIR, val: $HOME/.env/nvim3/bin/python, if: '[ -d $HOME/.env/nvim3 ]'}
  - {key: NVIM_PY3_DIR, val: which python3, eval: true, if: '[ ! -d $HOME/.env/nvim3 ]'}
  - {key: PIPX_BIN_DIR, val: $HOME/.local/bin}
  - {key: PIPENV_VENV_IN_PROJECT, val: 1}
  - {key: EDITOR, val: which nvim >/dev/null && echo "nvim" || echo "vim", eval: true}
  - {key: VISUAL, val: $EDITOR}
  - {key: VIM_COLOR, val: PaperColor-dark}
  - {key: NVIM_COLOR, val: PaperColor-dark}
  # FZF
  - {key: FZF_TMUX, val: 1}
  - {key: FZF_TMUX_HEIGHT, val: 40%}
  - {key: FZF_DEFAULT_COMMAND, val: fd -t f -HL --color=always --strip-cwd-prefix}
  - {key: FZF_DEFAULT_OPTS, val: --ansi --border --reverse --height='$FZF_TMUX_HEIGHT'}
  - key: FZF_PREVIEW_OPTS
    val:
      --ansi --bind='?:toggle-preview' --bind='ctrl-u:preview-page-up' --bind='ctrl-d:preview-page-down'
      --preview-window='right:60%:wrap' --preview='bat --color=always --style=full --line-range :300 {} 2>/dev/null || tree -C {}'
  - {key: FZF_FIND_FILE_COMMAND, val: $FZF_DEFAULT_COMMAND}
  - {key: FZF_FIND_FILE_OPTS, val: $FZF_PREVIEW_OPTS}
  - {key: FZF_OPEN_COMMAND, val: $FZF_DEFAULT_COMMAND}
  - {key: FZF_OPEN_OPTS, val: $FZF_PREVIEW_OPTS}
  - {key: FZF_PREVIEW_FILE_CMD, val: $FZF_PREVIEW_OPTS}
  - {key: FZF_PREVIEW_DIR_CMD, val: eza --color=always}
  - {key: FZF_ENABLE_OPEN_PREVIEW, val: 1}
  - {key: FZF_CD_COMMAND, val: fd -L -t d --color=always}
  - {key: FZF_CD_WITH_HIDDEN_COMMAND, val: '"$FZF_CD_COMMAND -H"', quote: false}
  - {key: FZF_CD_OPTS, val: "--ansi --preview-window right:60% --preview '$FZF_PREVIEW_DIR_CMD {}' -p 60%,60%"}
  - {key: FZF_CTRL_T_COMMAND, val: $FZF_DEFAULT_COMMAND}
  - {key: FZF_CTRL_T_OPTS, val: $FZF_PREVIEW_OPTS}
  - {key: FZF_COMPLETION_OPTS, val: $FZF_PREVIEW_OPTS}
  - {key: SKIM_DEFAULT_COMMAND, val: rg --files --no-messages --hidden}
  - {key: FZY_DEFAULT_COMMAND, val: fd -t f -HL --strip-cwd-prefix}
  - {key: GOPATH, val: $HOME/go}
  - {key: GOBIN, val: $HOME/go/bin}
  - {key: RIPGREP_CONFIG_PATH, val: $XDG_CONFIG_HOME/ripgrep/ripgreprc}
  - {key: CARGO_HOME, val: $HOME/.cargo}
  - {key: VCPROMPT_FORMAT, val: '%b@%r %m %u'}
  - {key: VCP_FORMAT, val: '%n %b@%c%B%A%o|%s%m%u'}
  - {key: ANSIBLE_CONFIG, val: $HOME/.ansible/ansible.cfg}
  - {key: ASDF_SKIP_RESHIM, val: 1}
  - {key: TIGRC_USER, val: $XDG_CONFIG_HOME/tig/tigrc}
  - key: LF_ICONS
    val: '''tw=:st=:ow=:dt=:di=:fi=:ln=:or=:ex=:*.c=:*.cc=:*.clj=:*.coffee=:*.cpp=:*.css=:*.d=:*.dart=:*.erl=:*.exs=:*.fs=:*.go=:*.h=:*.hh=:*.hpp=:*.hs=:*.html=:*.java=:*.jl=:*.js=:*.json=:*.lua=:*.md=:*.php=:*.pl=:*.pro=:*.py=:*.rb=:*.rs=:*.scala=:*.ts=:*.vim=:*.cmd=:*.ps1=:*.sh=:*.bash=:*.zsh=:*.fish=:*.tar=:*.tgz=:*.arc=:*.arj=:*.taz=:*.lha=:*.lz4=:*.lzh=:*.lzma=:*.tlz=:*.txz=:*.tzo=:*.t7z=:*.zip=:*.z=:*.dz=:*.gz=:*.lrz=:*.lz=:*.lzo=:*.xz=:*.zst=:*.tzst=:*.bz2=:*.bz=:*.tbz=:*.tbz2=:*.tz=:*.deb=:*.rpm=:*.jar=:*.war=:*.ear=:*.sar=:*.rar=:*.alz=:*.ace=:*.zoo=:*.cpio=:*.7z=:*.rz=:*.cab=:*.wim=:*.swm=:*.dwm=:*.esd=:*.jpg=:*.jpeg=:*.mjpg=:*.mjpeg=:*.gif=:*.bmp=:*.pbm=:*.pgm=:*.ppm=:*.tga=:*.xbm=:*.xpm=:*.tif=:*.tiff=:*.png=:*.svg=:*.svgz=:*.mng=:*.pcx=:*.mov=:*.mpg=:*.mpeg=:*.m2v=:*.mkv=:*.webm=:*.ogm=:*.mp4=:*.m4v=:*.mp4v=:*.vob=:*.qt=:*.nuv=:*.wmv=:*.asf=:*.rm=:*.rmvb=:*.flc=:*.avi=:*.fli=:*.flv=:*.gl=:*.dl=:*.xcf=:*.xwd=:*.yuv=:*.cgm=:*.emf=:*.ogv=:*.ogx=:*.aac=:*.au=:*.flac=:*.m4a=:*.mid=:*.midi=:*.mka=:*.mp3=:*.mpc=:*.ogg=:*.ra=:*.wav=:*.oga=:*.opus=:*.spx=:*.xspf=:*.pdf=:*.nix='''
  - {key: _ZO_FZF_OPTS, val: --select-1}
  - {key: THEFUCK_OVERRIDDEN_ALIASES, val: 'git,cat'}
  - {key: EZA_COLORS, val: 'da=38\;5\;252'}
  - key: LS_COLORS
    val: |
      file="$HOME/.dircolors"
      if [ -f "$file" ]; then
      dircolors -c "$file" | sed s/"setenv LS_COLORS "//
      fi
    eval: true
    if: '[ $(uname -s) != "Darwin" ]'  # No `dircolors` installed on MacOS
    shell: [bash, fish, nu]

env_aliases:
  - {key: weahter, val: weather}
  - {key: g, val: git}
  - {key: ga, val: fgit add}
  - {key: gc, val: git commit}
  - {key: gca, val: git commit -a}
  - {key: gpl, val: git pull}
  - {key: gpa, val: 'fd -HIg0 -t d .git | fzf-tmux -m --read0 --print0 | xargs -P8 -0I{} git --git-dir={} pull'}
  - {key: gph, val: git push}
  - {key: gs, val: git status -s}
  - {key: gcp, val: git commit && git push}
  - {key: gac, val: fgit add && git commit}
  - {key: gsync, val: git pull && git add . && git commit && git push}
  - {key: gco, val: git checkout}
  - {key: gcom, val: git checkout master}
  - {key: gcol, val: git checkout $(git describe --tags $(git rev-list --tags --max-count=1))}
  - {key: gd, val: git diff}
  - {key: gdf, val: fgit diff}
  - {key: gst, val: fgit status}
  - {key: vg, val: $EDITOR +"packadd vim-fugitive" +G +"wincmd o"}
  - {key: glog, val: git log --oneline --decorate --graph --all}
  - {key: grst, val: git reset --hard origin/master}
  - {key: gsub, val: git submodule foreach --recursive git pull origin master}
  - {key: gu, val: __git_fzf_git_unstage}
  - {key: grmi, val: git rm --cached}
  - {key: gsp, val: git stash && git pull && git stash pop}
  - {key: vid, val: $XDG_CONFIG_HOME/nvim}
  - {key: ffn, val: $XDG_CONFIG_HOME/fish/functions}
  - {key: fcm, val: $XDG_CONFIG_HOME/fish/completions}
  - {key: fcd, val: $XDG_CONFIG_HOME/fish/conf.d}
  - {key: bcd, val: $XDG_CONFIG_HOME/bash/conf.d}
  - {key: bfd, val: $XDG_CONFIG_HOME/bash/functions}
  - {key: zcd, val: $XDG_CONFIG_HOME/zsh/conf.d}
  - {key: zfd, val: $XDG_CONFIG_HOME/zsh/functions}
  - {key: sfd, val: $XDG_CONFIG_HOME/shell/functions}
  - {key: ssd, val: $XDG_CONFIG_HOME/shell/scripts}
  - {key: scd, val: $XDG_CONFIG_HOME/shell/conf.d}
  - {key: bup, val: brew update && brew upgrade && brew cleanup, if: which brew}
  - {key: brewdesc, val: brew leaves | xargs brew desc --eval-all, if: which brew}
  - {key: xo, val: xonsh, if: which xonsh}
  - {key: lp, val: lpass, if: which lpass}
  - {key: vc, val: vcprompt-rs, if: which vcprompt-rs}
  - {key: vcp, val: vcprompt -f "%b %r %p %u %m", if: which vcprompt}
  - {key: vct, val: vctest -f "%b %r %p %u %m"}
  - {key: lg, val: lazygit, if: which lazygit}
  - {key: ts, val: tig status, if: which tig}
  - {key: h, val: $HOME}
  - {key: rmdir, val: safe-rm -rf, if: which safe-rm}
  - {key: rmdir, val: rm -rf, if: ! which safe-rm}
  - {key: rm, val: safe-rm, if: which safe-rm}
  - {key: version, val: cat /etc/os-release}
  - {key: lookbusy, val: command cat /dev/urandom | hexdump -C | grep "ca fe"}
  - {key: mv, val: mv -v}
  - {key: rmlink, val: find -maxdepth 1 -xtype l -print0 | xargs -0p rm}
  - {key: upd, val: ansible-playbook -c local -l $(uname -n) $HOME/.ansible/site.yml, if: '[ $(uname -s) != "Darwin" ]'}
  - {key: ans, val: ansible-playbook -c local -l $(uname -n), if: '[ $(uname -s) != "Darwin" ]'}
  - {key: upd, val: ansible-playbook -c local -l $(hostname -s) $HOME/.ansible/site.yml, if: '[ $(uname -s) == "Darwin" ]'}
  - {key: ans, val: ansible-playbook -c local -l $(hostname -s), if: '[ $(uname -s) == "Darwin" ]'}
  - {key: ls, val: command ls -h --color=auto, shell: [bash, zsh]}
  - {key: ll, val: ls -lah --color=auto, if: ! which eza}
  - {key: ll, val: eza, if: which eza}
  - {key: lso, val: stat -c "%a %A %3h %5U %5G %n" *, if: ! which eza && ! which lsd}
  - {key: lso, val: eza --octal-permissions, if: which eza && ! which lsd}
  - {key: lso, val: lsd -l --git --permission octal, if: which lsd}
  - {key: d, val: ls -lah --color=auto, if: ! which lsd}
  # - {key: d, val: lsd -l --git, if: which lsd}
  - {key: d, val: eza -G --git, if: which eza}
  - {key: x, val: eza -F -G -TL1, if: which eza}
  - {key: l, val: eza --git --octal-permissions, if: which eza && ! which lsd}
  - {key: l, val: lsd -l --git --permission octal, if: which lsd}
  - {key: xx, val: eza -F -G -TL2, if: which eza}
  - {key: xxx, val: eza -F -G -TL3, if: which eza}
  - {key: q, val: exit}
  - {key: quit, val: exit}
  - {key: che, val: chmod +x}
  - {key: db, val: dropbox, if: which dropbox.py}
  - {key: dbr, val: dropbox stop; sleep 3; dropbox start, if: which dropbox.py}
  - {key: fe, val: fzf-edit, shell: [bash, zsh]}
  - {key: frg, val: fzf_rg}
  - {key: t, val: todo}
  - {key: tc, val: TODOTXT_FINAL_FILTER=cat todo}
  - {key: tt, val: todo.sh -d ~/git/todors/tests/todo.cfg}
  - {key: td, val: todors}
  - {key: te, val: $EDITOR $XDG_CONFIG_HOME/tmux/tmux.conf}
  - {key: n, val: nvim, if: which nvim}
  - {key: ns, val: nvim -S, if: which nvim}
  - {key: vim, val: which vim >/dev/null && echo "vim" || echo "nvim", eval: true}
  - {key: vv, val: command vim, if: which vim}
  - {key: sv, val: sudo -E env PATH="$PATH" $EDITOR}
  - {key: vet, val: $EDITOR $HOME/.ansible/roles/env/defaults/main.yml}
  - {key: brc, val: $EDITOR $HOME/.bashrc}
  - {key: zshc, val: $EDITOR $ZDOTDIR/.zshrc}
  - {key: rel, val: ' exec $CURRENT_SHELL -l'}
  - {key: cup, val: rustup update && cargo install-update --all --git}
  # Task runners
  - {key: j, val: just}
  - {key: ta, val: task, if: which task}
  - {key: ma, val: mask, if: which mask}
  - {key: gp, val: git-prompt}
  - {key: git, val: hub, shell: [bash, zsh], if: which hub}
  # Grep
  - {key: grep, val: grep -R --color=auto, shell: [bash, zsh]}
  - {key: fgrep, val: fgrep --color=auto, shell: [bash, zsh]}
  - {key: egrep, val: egrep --color=auto, shell: [bash, zsh]}
  - {key: todo, val: todo.sh, shell: [bash, zsh]}
  - {key: eza, val: command eza -la --group-directories-first --icons --color-scale, shell: [bash, zsh]}
  # Dir navigation
  - {key: ..., val: cd ../.., shell: [bash, zsh]}
  - {key: ...., val: cd ../../.., shell: [bash, zsh]}
  - {key: ....., val: cd ../../../.., shell: [bash, zsh]}
  # Cat
  - {key: cat, val: ccat, if: which ccat, shell: [bash, zsh]}
  - {key: cat, val: gcat, if: which gcat, shell: [bash, zsh]}
  - {key: cat, val: bat, if: which bat, shell: [bash, zsh]}
