---
# master level playbook
- import_playbook: playbooks/dotfiles.yml
- import_playbook: playbooks/pkg.yml
- import_playbook: playbooks/asdf.yml
- import_playbook: playbooks/env.yml
- import_playbook: playbooks/fish.yml
- import_playbook: playbooks/fzy.yml
- import_playbook: playbooks/fd.yml
# todo: don't need to use this on mac. Best way?
- import_playbook: playbooks/gh-cli.yml
- import_playbook: playbooks/hub.yml
- import_playbook: playbooks/luals.yml
- import_playbook: playbooks/mosh.yml
- import_playbook: playbooks/nvim.yml
- import_playbook: playbooks/pipx.yml
- import_playbook: playbooks/rust.yml
- import_playbook: playbooks/ssh.yml
- import_playbook: playbooks/tmux.yml
- import_playbook: playbooks/lsd.yml
- import_playbook: playbooks/zoxide.yml
- import_playbook: playbooks/just.yml
