#!/usr/bin/env bash
# shellcheck disable=SC2086
# Calculate tmux status bar on right side

HOSTNAME=$(uname -n)
USERNAME=${USER:-$(whoami)}
HOST=" ${HOSTNAME/.local/}"
WIDTH=$(tmux display -p '#{client_width}')
TABS=$(tmux display -p '#{session_windows}')
SMALL=40
MEDIUM=100
MEDIUM_LARGE=150
LARGE=200

# Separators
RSUB="${RSUB:-|}"

TMUX_TOP="$HOME/go/bin/tmux-top"
SYSINFO="$HOME/.cargo/bin/sysinfo"
# TMUX_MEM_CPU="$HOME/.tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load"
UP=$("$HOME/.config/tmux/_uptime")

# Status commands
if [[ -x $TMUX_MEM_CPU ]]; then
    SYSLOAD=$($TMUX_MEM_CPU --colors --interval 2)
else
    if [[ -x $SYSINFO ]]; then
        memusage_cmd='memory'
        loadavg_cmd='load'
        uptime_cmd='uptime -p'
        temp_cmd='temp 2>/dev/null'
        # cpu_usage_cmd='cpu -i 2 2>/dev/null'
        if [[ $WIDTH -lt $MEDIUM_LARGE ]]; then
            memusage_cmd='memory -u'
            loadavg_cmd='load -n 1'
        fi
        MEMUSAGE=$($SYSINFO $memusage_cmd)
        LOADAVG=$($SYSINFO $loadavg_cmd)
        UP=$($SYSINFO $uptime_cmd)
        CPUTEMP=$($SYSINFO $temp_cmd)
        # CPUUSAGE=$($SYSINFO $cpu_usage_cmd)
    else
        if [[ -x $TMUX_TOP ]]; then
            MEMUSAGE=$("$TMUX_TOP" m)
            LOADAVG=$("$TMUX_TOP" l)
        # elif [[ -x $TMUX_MEM_CPU ]]; then
        #     MEMUSAGE=$(eval "$TMUX_MEM_CPU" -g 0 -m 0 -i 2)
        else
            MEMUSAGE=$("$HOME/.config/tmux/_memusage" 2>/dev/null)
            LOADAVG=$("$HOME/.config/tmux/_loadavg")
        fi
    fi
    SYSLOAD="$MEMUSAGE $LOADAVG"
fi

if [[ -n $CPUTEMP ]]; then
    SYSLOAD="$SYSLOAD $CPUTEMP"
fi

if [[ $WIDTH -gt $MEDIUM ]]; then
    TIME+="#[fg=colour252,bg=colour236,noitalics,nounderscore] $(date +'%R')"
    LOAD="#[fg=colour10,bg=default,nobold,noitalics,nounderscore]$SYSLOAD"

    if [[ $WIDTH -gt $LARGE ]] || [[ $TABS -lt 5 ]]; then
        UPTIME="#[fg=yellow,bg=default,nobold,noitalics,nounderscore]$UP"
        UPTIME+=" #[fg=colour241,bg=default,nobold,noitalics,nounderscore]$RSUB"
    fi
fi

if [[ $WIDTH -ge $SMALL ]]; then
    USER="#[fg=colour31,bg=colour236,nobold,noitalics,nounderscore]$RSEP"
    USER+="#[fg=colour231,bg=colour31,bold,noitalics,nounderscore] $USERNAME"
    UNAME="#[fg=colour252,bg=colour31,nobold,noitalics,nounderscore]$RSEP"
    UNAME+="#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $HOST"
    UNAME+=" #[]" # Easy way to allow space at end without bash eating it
fi

# Allow bash to mangle extra spaces and avoid piping to tr
echo $UPTIME $MEM_CPU $LOAD $DATE $TIME $USER $UNAME
