#!/usr/bin/env bash
# Colorize man pages

PATH="$(path_remove "$(dirname "$0")")"

reset=$'\e[0m'
underline=$'\e[4m'
red=$'\e[38;5;1m'
blue=$'\e[38;5;74m'
light_blue=$'\e[38;5;146m'
gray=$'\e[38;5;246m'

export LESS_TERMCAP_mb="$red"
export LESS_TERMCAP_md="$blue"
export LESS_TERMCAP_me="$reset"
export LESS_TERMCAP_so="$gray"
export LESS_TERMCAP_se="$reset"
export LESS_TERMCAP_us="$light_blue$underline"
export LESS_TERMCAP_ue="$reset"

exec man "$@"
