#!/usr/bin/env bash
# Build neovim from source

# if not root, run as root
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
    exit
fi

src_dir="$1"

if [ ! -d "$src_dir" ]; then
    echo "Source dir not found at $src_dir! Aborting..." >&2
    exit 1
fi
echo "Building Neovim from local source repo at $src_dir..."

cd "$src_dir" || exit 1

# Build bundled deps
[ -d .deps ] && rm -rf .deps
mkdir .deps && cd .deps &&
    {
        cmake ../third-party && make
    } || exit 1

# Build Neovim
cd "$src_dir" || exit 1
[ -d build ] && rm -rf build &&
    {
        make distclean
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        sudo make install
    }

if [ $? -eq 0 ]; then
    echo "Neovim build complete!"
else
    echo "Neovim build failed!" >&2
fi
