#!/usr/bin/env bash
# Build vim from source

# if not root, run as root
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
    exit
fi

src_dir="$1"

if [ ! -d "$src_dir" ]; then
    echo "Source dir not found at $src_dir! Aborting..." >&2
    exit 1
fi
echo "Building vim from local source repo at $src_dir..."

# Build vim
case "$HOSTNAME" in
io)
    py3_dir="/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu"
    ;;
joppa)
    py3_dir=$(python3.5-config --configdir)
    ;;
titan)
    py3_dir="/home/pi/.pyenv/versions/3.7.2/lib/python3.7/config-3.7m-arm-linux-gnueabihf"
    ;;
jupiter)
    py3_dir="/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu"
    ;;
*)
    echo "Need to set python3 config dir for this host." >&2 &&
        exit 1
    ;;
esac

venv="$VIRTUAL_ENV"

if [ -n "$venv" ]; then
    echo "Deactivating virtual env..."
    deactivate
fi

cd "$src_dir" &&
    {
        ./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-python3interp=yes \
            --with-python3-config-dir=$py3_dir \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-cscope \
            --prefix=/usr/local

        make VIMRUNTIMEDIR=/usr/local/share/vim/vim81
        sudo make install
    } || exit 1

if [ -n "$venv" ]; then
    echo "Reactivating virtual env..."
    . "$venv/bin/activate"
fi

if [ $? -eq 0 ]; then
    echo "Vim build complete!"
else
    echo "Vim build failed!" >&2
fi
