#!/usr/bin/env bash
# Update all apt packages

# if not root, run as root
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
    exit
fi

apt update
apt -y dist-upgrade
apt -y autoremove
apt clean
apt purge -y $(dpkg -l | awk '/^rc/ { print $2 }')
