#!/usr/bin/env bash

# use cat alternatives if installed

if [ -x /usr/bin/bat ]; then
    /usr/bin/bat "$@"
elif [ -x "$GOBIN/ccat" ]; then
    "$GOBIN/ccat" --bg=dark "$@"
elif [ -x /usr/local/bin/gcat ]; then
    /usr/local/bin/gcat "$@"
else
    /bin/cat "$@"
fi
