#!/usr/bin/env bash

# use cat alternatives if installed

if [ -x "$CARGO_HOME/bin/bat" ]; then
    "$CARGO_HOME/bin/bat" "$@"
elif [ -x "$GOBIN/ccat" ]; then
    "$GOBIN/ccat" --bg=dark "$@"
elif [ -x /usr/local/bin/gcat ]; then
    /usr/local/bin/gcat "$@"
else
    /bin/cat "$@"
fi
