#!/usr/bin/env bash

# use cat alternatives if installed

PATH="$(path_remove "$PWD")"

if [ -n "$(command -v bat 2>/dev/null)" ]; then
    bat "$@"
elif [ -n "$(command -v ccat 2>/dev/null)" ]; then
    ccat "$@"
elif [ -n "$(command -v gcat 2>/dev/null)" ]; then
    gcat "$@"
else
    cat "$@"
fi
