#!/usr/bin/env bash
fco_preview() {
    local tags branches target
    tags=$(
        git tag | awk '{print "\x1b[31;1mtag\x1b[m\t" $1}'
    ) || return
    branches=$(
        git branch --all | grep -v HEAD |
            sed "s/.* //" | sed "s#remotes/[^/]*/##" |
            sort -u | awk '{print "\x1b[34;1mbranch\x1b[m\t" $1}'
    ) || return
    target=$(
        (
            echo "$tags"
            echo "$branches"
        ) |
            fzf-tmux --no-hscroll --no-multi --delimiter="\t" -n 2 \
                --ansi --preview="git log -200 --pretty=format:%s $(echo {+2..} | sed 's/$/../')"
    ) || return
    git checkout "$(echo "$target" | awk '{print $2}')"
}

fco_preview "$@"
