#!/usr/bin/env bash
# list directories in $PATH, press [enter] on an entry to list the executables inside.
# press [escape] to go back to directory listing, [escape] twice to exit completely

# TODO: use preview command to show all executables in dir

loc=$(echo "$PATH" | sed -e $'s/:/\\\n/g' | eval "fzf-tmux ${FZF_DEFAULT_OPTS} --header='[find:path]'")

if [ -d "$loc" ]; then
    rg --files "$loc" | rev | cut -d"/" -f1 | rev | eval "fzf-tmux ${FZF_DEFAULT_OPTS} --header='[find:exe] => ${loc}' >/dev/null"
    fpath
fi
