#!/usr/bin/env bash
# Fetch repo and see if it has changes

git_dir="${1:-.}"
command git -C "$git_dir" fetch

head_hash=$(command git -C "$git_dir" rev-parse HEAD)
upstream_hash=$(command git -C "$git_dir" rev-parse 'master@{upstream}')

if [ "$head_hash" != "$upstream_hash" ]; then
    exit 0
else
    exit 1
fi
