#!/bin/bash
# Remove traces of something installed with `go get`
goclean() {
    local pkg=$1
    shift || return 1
    local ost
    local cnt

    # Clean removes object files from package source directories (ignore error)
    go clean -i "$pkg" &>/dev/null

    # Set local variables
    [[ "$(uname -m)" == "x86_64" ]] &&
        ost="$(uname)"
    ost="${ost,,}_amd64" &&
        cnt="${pkg//[^\/]/}"

    # Delete the source directory and compiled package directory(ies)
    if (("${#cnt}" == "2")); then
        rm -rf "${GOPATH%%:*}/src/${pkg%/*}"
        rm -rf "${GOPATH%%:*}/pkg/${ost}/${pkg%/*}"
    elif (("${#cnt}" > "2")); then
        rm -rf "${GOPATH%%:*}/src/${pkg%/*/*}"
        rm -rf "${GOPATH%%:*}/pkg/${ost}/${pkg%/*/*}"
    fi
}
