#!/usr/bin/env python3
"""Get location from current IP or SSH IP."""
import logging
import os
import pprint

import ipinfo

logging.basicConfig(level=logging.DEBUG)
LOG = logging.getLogger(__name__)


def get_token() -> str:
    """Retrieve secret access token from disk."""
    file = os.path.expanduser("~/.ipinfo_token")
    token = ""
    try:
        with open(file, "r") as f:
            token = f.read()
    except FileNotFoundError:
        print(f"ipinfo token file not found: {file}. Aborting!")
        return ""
    else:
        return token.strip("\n")


def get_ipinfo():
    """Get response from ipinfo.io."""
    #  ssh_ip = os.environ.get("SSH_CONNECTION")
    token = get_token()
    LOG.debug("Token from disk: %s", token)
    handler = ipinfo.getHandler(token)
    details = handler.getDetails()
    LOG.debug("Response:\n%s", pprint.pformat(details.all))


def main():
    #  print(get_ip())
    get_ipinfo()


if __name__ == "__main__":
    main()
