#!/bin/sh
# https://github.com/wookayin/is_mosh/

has_ancestor_mosh() {
    pstree -ps "$1" | grep mosh-server
}

is_mosh() {
    # local tmux_current_session tmux_client_id pid mosh_found
    # argument handling
    for arg in "$@"; do
        case $arg in
        -v | --verbose) VERBOSE=YES ;;
        *) ;;
        esac
    done

    if [ -n "$TMUX" ]; then
        # current shell is under tmux
        tmux_current_session=$(tmux display-message -p '#S')
        tmux_client_id=$(tmux list-clients -t "${tmux_current_session}" -F '#{client_pid}')
        pid="$tmux_client_id"
    else
        pid="$$"
    fi

    mosh_found=$(has_ancestor_mosh $pid) # or empty if not found
    if [ -z "$mosh_found" ]; then
        return 1 # exit code 1: not mosh
    fi

    [ -n "$VERBOSE" ] && echo "mosh"
    return 0 # exit code 0: is mosh
}

is_mosh "$@"
