#!/usr/bin/env bash
# Print $PATH with line breaks

# pathlines="${PATH//:/$'\n'}"
# echo "$pathlines"
# echo "-----------------"
# printf "\$PATH count: %d\n" "$(echo "$pathlines" | wc -l)"

echo "$PATH" | tr ":" "\n" | nl
