#!/usr/bin/env python3
"""Print PATH elements and lengths to the terminal."""
import os

path = os.environ.get("PATH").split(":")

for i, p in enumerate(path, 1):
    plen = len(p)
    print("{:2d}: len={:3d} |{}|".format(i, plen, p))
