#!/usr/bin/env bash

current_shell=$(basename $SHELL)

# If arg is supplied, use that as shell instead
if [ -n "$1" ]; then
    current_shell="$1"
fi

file="$HOME/.no_${current_shell}_tmux_login"

if [ -f "$file" ]; then
    rm $file && echo "Deleted $file."
    return 0
else
    touch $file && echo "Created $file."
    echo -e $(echo -ne '\033[1;33m')
    echo "TMUX will not start on login until"
    echo "tmux_toggle is run again."
    echo -e $(echo -ne '\033[0m')
fi
