#!/bin/sh

SEP=
SEPE=

HOSTNAME=''

WIDTH=${1}

SMALL=40
MEDIUM=80

if [ "$WIDTH" -gt "$MEDIUM" ]; then
    if type mpc >/dev/null; then
        # TODO: add cpu/uptime/etc here
        MPD="#[fg=colour252,bg=default,nobold,noitalics,nounderscore]$SEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $(mpc current)"
        date_colour='colour252'
    fi
fi


if [ "$WIDTH" -ge "$SMALL" ]; then
    USER="#[fg=colour31,bg=colour236,nobold,noitalics,nounderscore]$SEP#[fg=colour231,bg=colour31,bold,noitalics,nounderscore] $(whoami)"
    UNAME="#[fg=colour252,bg=colour31,nobold,noitalics,nounderscore]$SEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $HOSTNAME $(uname -n)"
fi

MEM_CPU="#[fg=green,bg=default,nobold,noitalics,nounderscore] $($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load -g 0 -i 10)"
DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$SEP#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] $(date +'%D')"
TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$SEPE#[fg=colour252,bg=colour236,noitalics,nounderscore] $(date +'%I:%M %p')"

echo "$PREFIX $MPD $MEM_CPU $DATE $TIME $USER $UNAME " | sed 's/ *$/ /g'
