#!/usr/bin/env bash
# Update/build fish shell from source

src_dir="$HOME/src/fish-shell"

if git_repo_has_upstream_changes "$src_dir"; then
    command git -C "$src_dir" reset --hard origin/master \
    && _build_fish "$src_dir" 
else
    echo "Fish has no upstream changes." >&2
    exit 1
fi
