#!/usr/bin/env bash

# Download plugins for Vim and Neovim
if [ -x "$HOME/git/python/shell/vimsync.py" ]; then
    echo "Executing vimsync.py ... "
    $HOME/git/python/shell/vimsync.py $@
else
    echo "Executing bash function ... "
    if hash vim 2>/dev/null; then
        echo "Found Vim; updating plugins..."
        command vim +PlugInstall +qall
        echo "Plugins updated. Updating remote plugins..."
        command vim +UpdateRemotePlugins +qall
        echo "Vim updates complete."
    else
        echo "Vim binary not found!"
    fi
    if hash nvim 2>/dev/null; then
        echo "Found Neovim; updating plugins..."
        command nvim +PlugInstall +qall
        echo "Plugins updated. Updating remote plugins..."
        # Attempt to "open" typescript file before updating remote
        command nvim t.ts +UpdateRemotePlugins +qall
        echo "Neovim updates complete."
    else
        echo "Neovim binary not found!"
    fi
    echo "Vim/Neovim plugin sync complete."
fi
