#!/usr/bin/env bash
script="$HOME/git/python/shell/weather/weather.py"

if [ -x "$script" ]; then
    python "$script" $@
elif [ -e "$script" ]; then
    echo "Script exists but is not executable: $script"
    exit 1
else
    echo "Cannot find $script"
    exit 1
fi
