#!/usr/bin/env bash
script="$HOME/git/python/shell/weather/weather.py"
py3bin="$PYENV_ROOT/versions/weather/bin/python3"

[ ! -x "$py3bin" ] && echo "$py3bin not executable" && exit 1

if [ -x "$script" ]; then
    "$py3bin" "$script" "$@"
elif [ -e "$script" ]; then
    echo "Script exists but is not executable: $script"
    exit 1
else
    echo "Cannot find $script"
    exit 1
fi
