#!/usr/bin/env bash
# Load weather in terminal

# Formats:
#       ?format=1       One line output of temp
#       ?format=2       One line output of temp/wind
#       ?format=3       Same as 1 with loc
#       ?format=4       Same as 2 with loc

host="$(hostname)"

loc="75067"
[ "$host" = "jupiter" ] && loc="76207"
loc="${1:-$loc}"

curl "wttr.in/$loc"
