#!/usr/bin/env bash

command="${1:-}"
if [ "$#" -gt 0 ]; then
    shift
fi

case "$command" in
activate | deactivate | rehash | shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
*)
    command pyenv "$command" "$@"
    ;;
esac
