# File created by direnv.zsh
2to3() { asdf exec 2to3 $@ }
2to3-3.6() { asdf exec 2to3-3.6 $@ }
2to3-3.7() { asdf exec 2to3-3.7 $@ }
2to3-3.8() { asdf exec 2to3-3.8 $@ }
activate-global-python-argcomplete() { asdf exec activate-global-python-argcomplete $@ }
ansible-eval() { asdf exec ansible-eval $@ }
ansible-role() { asdf exec ansible-role $@ }
ansible-task() { asdf exec ansible-task $@ }
bash-language-server() { asdf exec bash-language-server $@ }
chardetect() { asdf exec chardetect $@ }
clasp() { asdf exec clasp $@ }
direnv() { asdf exec direnv $@ }
direnv_use_asdf() { asdf exec direnv_use_asdf $@ }
distro() { asdf exec distro $@ }
easy_install() { asdf exec easy_install $@ }
easy_install-2.7() { asdf exec easy_install-2.7 $@ }
easy_install-3.6() { asdf exec easy_install-3.6 $@ }
easy_install-3.7() { asdf exec easy_install-3.7 $@ }
easy_install-3.8() { asdf exec easy_install-3.8 $@ }
functions.zsh() { asdf exec functions.zsh $@ }
futurize() { asdf exec futurize $@ }
geocode() { asdf exec geocode $@ }
idle() { asdf exec idle $@ }
idle3() { asdf exec idle3 $@ }
idle3.6() { asdf exec idle3.6 $@ }
idle3.7() { asdf exec idle3.7 $@ }
idle3.8() { asdf exec idle3.8 $@ }
imagemin() { asdf exec imagemin $@ }
isort() { asdf exec isort $@ }
luafmt() { asdf exec luafmt $@ }
luajit() { asdf exec luajit $@ }
luajit-2.0.1() { asdf exec luajit-2.0.1 $@ }
lua-lsp() { asdf exec lua-lsp $@ }
luarocks() { asdf exec luarocks $@ }
luarocks-5.1() { asdf exec luarocks-5.1 $@ }
luarocks-admin() { asdf exec luarocks-admin $@ }
luarocks-admin-5.1() { asdf exec luarocks-admin-5.1 $@ }
neovim-node-host() { asdf exec neovim-node-host $@ }
node() { asdf exec node $@ }
npm() { asdf exec npm $@ }
npx() { asdf exec npx $@ }
pasteurize() { asdf exec pasteurize $@ }
pip() { asdf exec pip $@ }
pip2() { asdf exec pip2 $@ }
pip2.7() { asdf exec pip2.7 $@ }
pip3() { asdf exec pip3 $@ }
pip3.6() { asdf exec pip3.6 $@ }
pip3.7() { asdf exec pip3.7 $@ }
pip3.8() { asdf exec pip3.8 $@ }
pipx() { asdf exec pipx $@ }
prettier() { asdf exec prettier $@ }
pydoc() { asdf exec pydoc $@ }
pydoc3() { asdf exec pydoc3 $@ }
pydoc3.6() { asdf exec pydoc3.6 $@ }
pydoc3.7() { asdf exec pydoc3.7 $@ }
pydoc3.8() { asdf exec pydoc3.8 $@ }
pyls() { asdf exec pyls $@ }
python() { asdf exec python $@ }
python2() { asdf exec python2 $@ }
python2.7() { asdf exec python2.7 $@ }
python2.7-config() { asdf exec python2.7-config $@ }
python2.7-gdb.py() { asdf exec python2.7-gdb.py $@ }
python2-config() { asdf exec python2-config $@ }
python3() { asdf exec python3 $@ }
python3.6() { asdf exec python3.6 $@ }
python3.6-config() { asdf exec python3.6-config $@ }
python3.6-gdb.py() { asdf exec python3.6-gdb.py $@ }
python3.6m() { asdf exec python3.6m $@ }
python3.6m-config() { asdf exec python3.6m-config $@ }
python3.7() { asdf exec python3.7 $@ }
python3.7-config() { asdf exec python3.7-config $@ }
python3.7-gdb.py() { asdf exec python3.7-gdb.py $@ }
python3.7m() { asdf exec python3.7m $@ }
python3.7m-config() { asdf exec python3.7m-config $@ }
python3.8() { asdf exec python3.8 $@ }
python3.8-config() { asdf exec python3.8-config $@ }
python3.8-gdb.py() { asdf exec python3.8-gdb.py $@ }
python3-config() { asdf exec python3-config $@ }
python-argcomplete-check-easy-install-script() { asdf exec python-argcomplete-check-easy-install-script $@ }
python-argcomplete-tcsh() { asdf exec python-argcomplete-tcsh $@ }
python-config() { asdf exec python-config $@ }
pyvenv() { asdf exec pyvenv $@ }
pyvenv-3.6() { asdf exec pyvenv-3.6 $@ }
pyvenv-3.7() { asdf exec pyvenv-3.7 $@ }
register-python-argcomplete() { asdf exec register-python-argcomplete $@ }
smtpd.py() { asdf exec smtpd.py $@ }
table() { asdf exec table $@ }
tsc() { asdf exec tsc $@ }
tslint() { asdf exec tslint $@ }
tsserver() { asdf exec tsserver $@ }
typescript-language-server() { asdf exec typescript-language-server $@ }
userpath() { asdf exec userpath $@ }
virtualenv() { asdf exec virtualenv $@ }
wheel() { asdf exec wheel $@ }
yarn() { asdf exec yarn $@ }
yarnpkg() { asdf exec yarnpkg $@ }
