alias cp='cp -i'
alias dotdrop='~/dotfiles/dotdrop.sh'
alias dotgit='git -C ~/dotfiles'
alias dotsync='dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install'
alias egrep='egrep --color=auto'
alias exif='exit'
alias fgrep='fgrep --color=auto'
alias gcp='cd ~/git/google-apps-script/sheets/convention-personnel'
alias gcpr='cd ~/git/google-apps-script/sheets/convention-personnel-reports'
alias gdiff='git diff'
alias gdot='cd ~/dotfiles/dotfiles'
alias gdspw='cd ~/git/google-apps-script/sheets/dspw'
alias gdspwe='cd ~/git/google-apps-script/sheets/dspw-email'
alias gfst='cd ~/git/google-apps-script/sheets/fs-time'
alias ggas='cd ~/git/google-apps-script/sheets'
alias glog='vim +GV'
alias gmg='git stash && git pull && git stash pop'
alias gph='git push'
alias gpl='git pull'
alias gpython='cd ~/git/python'
alias grep='grep --color=auto'
alias gst='git status -s'
alias gsub='git submodule foreach --recursive git pull origin master'
alias h='cd ~/'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'
alias ls='ls -h --color=auto --group-directories-first'
alias mv='mv -i'
alias q='exit'
alias r='cd /'
alias rm='rm -I'
alias rmdir='rm -rf'
alias v='nvim'
alias vdot='cd ~/dotfiles/dotfiles/.vim/config'
alias vim='nvim'
alias xo='xonsh'
