#!/usr/bin/env bash

temp_file="/sys/devices/virtual/thermal/thermal_zone0/temp"
temp=0

if [ -f "$temp_file" ]; then
    temp="$(cat $temp_file)"
fi

# echo "scale=1; ($temp / 1000.0)" | bc # Celsius
echo "scale=1; ($temp / 1000.0)*9/5+32" | bc # Fahrenheit
