#!/usr/bin/env bash
  case $(uname -s) in
    *Darwin*)
      echo "$(sysctl -q -n vm.loadavg | cut -d' ' -f 2-4)"
      ;;
    *Linux*)
      echo "$(cut -d' ' -f 1-3 < /proc/loadavg)"
      ;;
    *OpenBSD*)
      echo "$(sysctl -q -n vm.loadavg | cut -d' ' -f 1-3)"
      ;;
  esac
