#!/bin/sh

cache_file=~/.tmux_weather
cache_ttl=300
weather_bin=$HOME/bin/wttr

weather() {
    if [ -f "$cache_file" ]; then
        read -r existing <$cache_file
        echo "$existing"

        NOW=$(date +%s)
        MOD=$(date -r "$cache_file" +%s)
        if [ $((NOW - MOD)) -le $cache_ttl ]; then
            return
        fi
    fi
    if [ -x "$weather_bin" ]; then
        # GEO=$(curl -s https://ipinfo.io | jq -r '.loc')
        GEO=76207
        $weather_bin $GEO 3 >$cache_file
    else
        echo "TMUX weather: \`$weather_bin' is not accessible"
    fi
}

weather
