#!/bin/sh

cache_file=~/.tmux_weather
cache_ttl=300
weather_bin=$HOME/bin/wttr

weather() {
    if [ -f "$cache_file" ]; then
        NOW=$(date +%s)
        MOD=$(date -r "$cache_file" +%s)
        if [ $((NOW - MOD)) -gt $cache_ttl ]; then
            rm "$cache_file"
        fi
    elif [ -x "$weather_bin" ]; then
        # GEO=$(curl -s https://ipinfo.io | jq -r '.loc')
        GEO=76207
        $weather_bin $GEO 3 >"$cache_file"
    else
        echo "$weather_bin is not executable!"
    fi
    /bin/cat "$cache_file"
}

weather
