#!/usr/bin/env bash

HOSTNAME=''
WIDTH="$(tmux display -p '#{client_width}')"
SMALL=40
MEDIUM=80
LARGE=200

# Separators
SP=' '
RSUB="${RSUB}"

TMUX_TOP="$HOME/go/bin/tmux-top"
SYSINFO="$HOME/.cargo/bin/sysinfo"

# Status commands
if [ -x "$SYSINFO" ]; then
    MEMUSAGE="$("$SYSINFO" memory -p)"
    LOADAVG="$("$SYSINFO" load)"
    UPTIME="$("$SYSINFO" uptime)"
    # CPUTEMP="$("$SYSINFO" temp)"
else
    if [ -x "$TMUX_TOP" ]; then
        MEMUSAGE="$("$TMUX_TOP" m)"
        LOADAVG="$("$TMUX_TOP" l)"
    else
        MEMUSAGE="$("$HOME"/.config/tmux/_memusage 2>/dev/null)"
        LOADAVG="$("$HOME"/.config/tmux/_loadavg)"
    fi
    UPTIME="$("$HOME/.config/tmux/_uptime")"
fi

if [ "$MEMUSAGE" = "0.0%" ]; then
    SYSLOAD="$LOADAVG"
else
    if [ "$WIDTH" -gt "$LARGE" ]; then
        SYSLOAD="$MEMUSAGE $LOADAVG"
    else
        SYSLOAD="$MEMUSAGE"
    fi
fi

if [ "$WIDTH" -gt "$MEDIUM" ]; then
    DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$RSEP#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore]$SP$(date +'%D')"
    TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$RSUB$SP#[fg=colour252,bg=colour236,noitalics,nounderscore]$(date +'%I:%M %p')"
    # CPUTEMP="#[fg=green,bg=default,nobold,noitalics,nounderscore]$CPUTEMP"
    LOAD="#[fg=colour241,bg=default,nobold,noitalics,nounderscore]$RSUB$SP#[fg=colour10,bg=default,nobold,noitalics,nounderscore]$SYSLOAD"
    UPTIME="#[fg=yellow,bg=default,nobold,noitalics,nounderscore]$UPTIME"
    # WEATHER="$("$HOME"/.config/tmux/_weather)"
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
    USER="#[fg=colour31,bg=colour236,nobold,noitalics,nounderscore]$RSEP#[fg=colour231,bg=colour31,bold,noitalics,nounderscore]$SP$(whoami)"
    UNAME="#[fg=colour252,bg=colour31,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore]$SP$HOSTNAME $(uname -n)"
fi

# # Final formatting
# if [ "$CPUTEMP" -gt 0 ]; then
#     CPUTEMP="$CPUTEMP°"
# else
#     CPUTEMP=""
# fi

echo " $UPTIME $LOAD $DATE $TIME $USER $UNAME" | sed 's/ *$/ /g'
