#!/bin/sh

SEP=
SEPE="|"

HOSTNAME=''

WIDTH=${1}

SMALL=40
MEDIUM=80

if [ "$WIDTH" -gt "$MEDIUM" ]; then
    SEP=''
    SEPE=''


    LOAD="#[fg=green,bg=default,nobold,noitalics,nounderscore]$($HOME/.config/tmux/_loadavg)"
    CPUTEMP="#[fg=green,bg=default,nobold,noitalics,nounderscore]$($HOME/.config/tmux/_cputemp)"
    DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$SEP#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] $(date +'%D')"
    TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$SEPE#[fg=colour252,bg=colour236,noitalics,nounderscore] $(date +'%I:%M %p')"
fi


if [ "$WIDTH" -ge "$SMALL" ]; then
    USER="#[fg=colour31,bg=colour236,nobold,noitalics,nounderscore]$SEP#[fg=colour231,bg=colour31,bold,noitalics,nounderscore] $(whoami)"
    UNAME="#[fg=colour252,bg=colour31,nobold,noitalics,nounderscore]$SEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $HOSTNAME $(uname -n)"
fi

# Final formatting
[ -n "$CPUTEMP" ] && CPUTEMP="$CPUTEMP°"

echo "$CPUTEMP $LOAD $DATE $TIME $USER $UNAME " | sed 's/ *$/ /g'
