#!/usr/bin/env bash

HOSTNAME=''
WIDTH="$(tmux display -p '#{client_width}')"
TABS="$(tmux list-windows | wc -l)"
SMALL=40
MEDIUM=80
MEDIUM_LARGE=150
LARGE=200

# Separators
SP=' '
RSUB="${RSUB}"

TMUX_TOP="$HOME/go/bin/tmux-top"
SYSINFO="$HOME/.cargo/bin/sysinfo"
# TMUX_MEM_CPU="$TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load"

# Status commands
if [ -x "$SYSINFO" ]; then
    memusage_cmd='memory'
    loadavg_cmd='load'
    uptime_cmd='uptime'
    temp_cmd='temp 2>/dev/null'
    # cpu_usage_cmd='cpu -i 2 2>/dev/null'
    if [ "$WIDTH" -lt "$MEDIUM_LARGE" ]; then
        memusage_cmd='memory -p'
        loadavg_cmd='load -n 1'
    fi
    MEMUSAGE="$(eval "$SYSINFO" "$memusage_cmd")"
    LOADAVG="$(eval "$SYSINFO" "$loadavg_cmd")"
    UP="$(eval "$SYSINFO" "$uptime_cmd")"
    CPUTEMP="$(eval "$SYSINFO" "$temp_cmd")"
    # CPUUSAGE="$(eval "$SYSINFO" "$cpu_usage_cmd")"
else
    if [ -x "$TMUX_TOP" ]; then
        MEMUSAGE="$("$TMUX_TOP" m)"
        LOADAVG="$("$TMUX_TOP" l)"
    else
        MEMUSAGE="$("$HOME"/.config/tmux/_memusage 2>/dev/null)"
        LOADAVG="$("$HOME"/.config/tmux/_loadavg)"
    fi
    UP="$("$HOME/.config/tmux/_uptime")"
fi

SYSLOAD="$MEMUSAGE $LOADAVG"

if [ -n "$CPUTEMP" ]; then
    SYSLOAD="$SYSLOAD $CPUTEMP"
fi

if [ "$WIDTH" -gt "$MEDIUM" ]; then
    DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$RSEP#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore]$SP$(date +'%D')"
    TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$RSUB$SP#[fg=colour252,bg=colour236,noitalics,nounderscore]$(date +'%I:%M %p')"
    # CPUTEMP="#[fg=green,bg=default,nobold,noitalics,nounderscore]$CPUTEMP"
    LOAD="#[fg=colour241,bg=default,nobold,noitalics,nounderscore]$RSUB$SP#[fg=colour10,bg=default,nobold,noitalics,nounderscore]$SYSLOAD"
    # LOAD="#[fg=colour241,bg=default,nobold,noitalics,nounderscore]$RSUB$SP#[fg=colour10,bg=default,noitalics,nounderscore]$($TMUX_MEM_CPU -i 2)"

    if [[ $TABS -lt 5 ]]; then
        UPTIME="#[fg=yellow,bg=default,nobold,noitalics,nounderscore]$UP"
        # WEATHER="$("$HOME"/.config/tmux/_weather)"
    fi
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
    USER="#[fg=colour31,bg=colour236,nobold,noitalics,nounderscore]$RSEP#[fg=colour231,bg=colour31,bold,noitalics,nounderscore]$SP$(whoami)"
    UNAME="#[fg=colour252,bg=colour31,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore]$SP$HOSTNAME $(uname -n)"
fi

# # Final formatting
# if [ "$CPUTEMP" -gt 0 ]; then
#     CPUTEMP="$CPUTEMP°"
# else
#     CPUTEMP=""
# fi

echo " $UPTIME $LOAD $DATE $TIME $USER $UNAME" | sed 's/ *$/ /g'
