#!/usr/bin/env python3
"""Remove non-essential bloat packages from fresh Raspian install."""
import logging
import platform
import shutil
import subprocess
import sys

logging.basicConfig(level=logging.DEBUG)

LOG = logging.getLogger(__name__)

pkgs = """
idle
python3-pygame
python-pygame
python-tk
idle3
python3-tk
python3-rpi.gpio
python-serial
python3-serial
python-picamera
python3-picamera
python3-pygame
python-pygame
python-tk
python3-tk
debian-reference-en
dillo
x2x
scratch
nuscratch
timidity
smartsim
penguinspuzzle
pistore
sonic-pi
python3-numpy
python3-pifacecommon
python3-pifacedigitalio
python3-pifacedigital-scratch-handler
python-pifacecommon
python-pifacedigitalio
oracle-java8-jdk
minecraft-pi
python-minecraftpi
wolfram-engine
"""

directories = """
/home/pi/Desktop
/home/pi/Documents
/home/pi/Downloads
/home/pi/Music
/home/pi/oldconffiles
/home/pi/Pictures
/home/pi/Public
/home/pi/python_games
/home/pi/Templates
/home/pi/Videos
"""


def handler(func, path, exc):
    """Handles errors from rmtree."""
    LOG.error("Error deleting %s: %s", path, exc[1])


def run():
    """Script entry point."""
    print("Removing the following extra default packages:\n{}".format(pkgs.strip()))
    pkg_list = pkgs.strip().split("\n")

    # Call apt in subshell
    apt_cmd = ["sudo", "apt-get", "-y", "remove", "--purge", *pkg_list]
    LOG.debug("Command: %s", apt_cmd)
    subprocess.run(apt_cmd)

    print(
        "Removing the following extra default directories\n{}".format(
            directories.strip()
        )
    )

    for dir in directories.strip().split("\n"):
        LOG.debug("Removing %s", dir)
        shutil.rmtree(dir, onerror=handler)

    print("Finished removing bloat!")


if __name__ == "__main__":
    system = platform.machine()
    if not system.startswith("arm"):
        LOG.critical("System type appears to be incompatibile: %s", system)
        sys.exit(1)
    else:
        run()
